version: '3.8'
services:

  #
  # A SQL database used by the Curity Identity Server
  #
  curity-data:
    image: postgres:13.2
    hostname: dbserver
    volumes:
      - ./components/idsvr/data-backup.sql:/docker-entrypoint-initdb.d/data-backup.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password1'
      POSTGRES_DB: 'idsvr'

  #
  # A standalone instance of the Curity Identity Server
  #
  curity-idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    hostname: idsvr
    ports:
     - 6749:6749
     - 8443:8443
    volumes:
     - ./components/idsvr/license.json:/opt/idsvr/etc/init/license/license.json
     - ./components/idsvr/config-backup.xml:/opt/idsvr/etc/init/config.xml
     - ./components/idsvr/log4j2.xml:/opt/idsvr/etc/log4j2.xml
     - ./target/opa-authorization-manager:/opt/idsvr/usr/share/plugins/opa-authorization-manager
    environment:
      PASSWORD: 'Password1'
      LOGGING_LEVEL: DEBUG

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
    - "8181:8181"
    volumes:
      - ./components/opa/policies/:/policies
    # command: "run --server --addr :8181 /policies"
    command: "run --server --addr :8181 --log-level debug /policies"
